// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper/scrapertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := scrapertest.NewNopSettings(scrapertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			if tt.name == "all_set" {
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.EmitV1SystemConventions", true))
				t.Cleanup(func() {
					featuregate.GlobalRegistry().Set("scraper.cpu.EmitV1SystemConventions", false)
				})
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.EmitV1SystemConventions", true))
				t.Cleanup(func() {
					featuregate.GlobalRegistry().Set("scraper.cpu.EmitV1SystemConventions", false)
				})
			}
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["system.cpu.frequency"] = mb.metricSystemCPUFrequency.config.AggregationStrategy
			aggMap["system.cpu.frequency@v1"] = mb.metricSystemCPUFrequencyV1.config.AggregationStrategy
			aggMap["system.cpu.time"] = mb.metricSystemCPUTime.config.AggregationStrategy
			aggMap["system.cpu.time@v1"] = mb.metricSystemCPUTimeV1.config.AggregationStrategy
			aggMap["system.cpu.utilization"] = mb.metricSystemCPUUtilization.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, "[WARNING] Please set `enabled` field explicitly for `system.cpu.frequency`: This metric will be disabled by default in a future release. Use system.cpu.frequency@v1 instead.", observedLogs.All()[expectedWarnings].Message)
				expectedWarnings++
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, "[WARNING] Please set `enabled` field explicitly for `system.cpu.time`: This metric will be disabled by default in a future release. Use system.cpu.time@v1 instead.", observedLogs.All()[expectedWarnings].Message)
				expectedWarnings++
			}
			if tt.name == "all_set" {
				expectedWarnings++ // attributes differ
				expectedWarnings++ // type differs
				expectedWarnings++ // attributes differ
			}
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			if tt.name != "all_set" {

				allMetricsCount++
				mb.RecordSystemCPUFrequencyDataPoint(ts, 1, "cpu-val")
			}

			allMetricsCount++
			mb.RecordSystemCPULogicalCountDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordSystemCPUPhysicalCountDataPoint(ts, 1)
			if tt.name != "all_set" {
				defaultMetricsCount++
				allMetricsCount++
				mb.RecordSystemCPUTimeDataPoint(ts, 1, "cpu-val", AttributeStateIdle)
			}

			allMetricsCount++
			mb.RecordSystemCPUUtilizationDataPoint(ts, 1, "cpu-val", AttributeStateIdle)
			if tt.name == "reaggregate_set" {
				mb.RecordSystemCPUUtilizationDataPoint(ts, 3, "cpu-val-2", AttributeStateInterrupt)
			}

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricSystemCPUFrequency.aggDataPoints)
				assert.Empty(t, mb.metricSystemCPUFrequencyV1.aggDataPoints)
				assert.Empty(t, mb.metricSystemCPUTime.aggDataPoints)
				assert.Empty(t, mb.metricSystemCPUTimeV1.aggDataPoints)
				assert.Empty(t, mb.metricSystemCPUUtilization.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "system.cpu.logical.count":
					assert.False(t, validatedMetrics["system.cpu.logical.count"], "Found a duplicate in the metrics slice: system.cpu.logical.count")
					validatedMetrics["system.cpu.logical.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of available logical CPUs.", mi.Description())
					assert.Equal(t, "{cpu}", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "system.cpu.physical.count":
					assert.False(t, validatedMetrics["system.cpu.physical.count"], "Found a duplicate in the metrics slice: system.cpu.physical.count")
					validatedMetrics["system.cpu.physical.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of available physical CPUs.", mi.Description())
					assert.Equal(t, "{cpu}", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "system.cpu.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["system.cpu.utilization"], "Found a duplicate in the metrics slice: system.cpu.utilization")
						validatedMetrics["system.cpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Difference in system.cpu.time since the last measurement per logical CPU, divided by the elapsed time (value in interval [0,1]).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						cpuAttrVal, ok := dp.Attributes().Get("cpu")
						assert.True(t, ok)
						assert.Equal(t, "cpu-val", cpuAttrVal.Str())
						stateAttrVal, ok := dp.Attributes().Get("state")
						assert.True(t, ok)
						assert.Equal(t, "idle", stateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["system.cpu.utilization"], "Found a duplicate in the metrics slice: system.cpu.utilization")
						validatedMetrics["system.cpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Difference in system.cpu.time since the last measurement per logical CPU, divided by the elapsed time (value in interval [0,1]).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["system.cpu.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("cpu")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("state")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
func TestVersionedMetrics(t *testing.T) {
	t.Run("system.cpu.frequency", func(t *testing.T) {
		tests := []struct {
			name               string
			disableOld         bool
			enableNew          bool
			expectLegacyMetric bool
			expectNewMetric    bool
			expectLegacyAttrs  bool
		}{
			{
				name:               "legacy_only",
				disableOld:         false,
				enableNew:          false,
				expectLegacyMetric: true,
				expectNewMetric:    false,
			},
			{
				name:               "dual_emission",
				disableOld:         false,
				enableNew:          true,
				expectLegacyMetric: false,
				expectNewMetric:    true,
				expectLegacyAttrs:  true,
			},

			{
				name:               "new_only",
				disableOld:         true,
				enableNew:          true,
				expectLegacyMetric: false,
				expectNewMetric:    true,
				expectLegacyAttrs:  false,
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.DontEmitV0SystemConventions", tt.disableOld))
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.EmitV1SystemConventions", tt.enableNew))
				t.Cleanup(func() {
					featuregate.GlobalRegistry().Set("scraper.cpu.DontEmitV0SystemConventions", false)
					featuregate.GlobalRegistry().Set("scraper.cpu.EmitV1SystemConventions", false)
				})

				start := pcommon.Timestamp(1_000_000_000)
				ts := pcommon.Timestamp(1_000_001_000)
				settings := scrapertest.NewNopSettings(scrapertest.NopType)
				mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, "all_set"), settings, WithStartTime(start))

				mb.RecordSystemCPUFrequencyDataPoint(ts, 1, "cpu-val")

				metrics := mb.Emit(WithResource(pcommon.NewResource()))

				// Count metrics by name and type
				var legacyFound, newFound bool
				for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
					ms := metrics.ResourceMetrics().At(ri).ScopeMetrics().At(0).Metrics()
					for mi := 0; mi < ms.Len(); mi++ {
						m := ms.At(mi)
						// Same emitted name, same type - distinguish by attributes
						if m.Name() == "system.cpu.frequency" {
							dp := m.Gauge().DataPoints().At(0)
							_, hasNewAttr := dp.Attributes().Get("cpu.logical_number")
							if hasNewAttr {
								// Has v1-specific attribute - this is the new metric
								newFound = true
								if tt.expectLegacyAttrs {
									_, hasCPU := dp.Attributes().Get("cpu")
									assert.True(t, hasCPU, "expected legacy attr cpu")
								}
							} else {
								// No v1-specific attribute - this is the legacy metric
								legacyFound = true
							}
						}
					}
				}
				assert.Equal(t, tt.expectLegacyMetric, legacyFound)
				assert.Equal(t, tt.expectNewMetric, newFound)
			})
		}
	})
	t.Run("system.cpu.time", func(t *testing.T) {
		tests := []struct {
			name               string
			disableOld         bool
			enableNew          bool
			expectLegacyMetric bool
			expectNewMetric    bool
			expectLegacyAttrs  bool
		}{
			{
				name:               "legacy_only",
				disableOld:         false,
				enableNew:          false,
				expectLegacyMetric: true,
				expectNewMetric:    false,
			},
			{
				name:               "dual_emission",
				disableOld:         false,
				enableNew:          true,
				expectLegacyMetric: false,
				expectNewMetric:    true,
				expectLegacyAttrs:  true,
			},

			{
				name:               "new_only",
				disableOld:         true,
				enableNew:          true,
				expectLegacyMetric: false,
				expectNewMetric:    true,
				expectLegacyAttrs:  false,
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.DontEmitV0SystemConventions", tt.disableOld))
				require.NoError(t, featuregate.GlobalRegistry().Set(
					"scraper.cpu.EmitV1SystemConventions", tt.enableNew))
				t.Cleanup(func() {
					featuregate.GlobalRegistry().Set("scraper.cpu.DontEmitV0SystemConventions", false)
					featuregate.GlobalRegistry().Set("scraper.cpu.EmitV1SystemConventions", false)
				})

				start := pcommon.Timestamp(1_000_000_000)
				ts := pcommon.Timestamp(1_000_001_000)
				settings := scrapertest.NewNopSettings(scrapertest.NopType)
				mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, "all_set"), settings, WithStartTime(start))

				mb.RecordSystemCPUTimeDataPoint(ts, 1, "cpu-val", AttributeStateIdle)

				metrics := mb.Emit(WithResource(pcommon.NewResource()))

				// Count metrics by name and type
				var legacyFound, newFound bool
				for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
					ms := metrics.ResourceMetrics().At(ri).ScopeMetrics().At(0).Metrics()
					for mi := 0; mi < ms.Len(); mi++ {
						m := ms.At(mi)
						// Same emitted name, different types - distinguish by type
						if m.Name() == "system.cpu.time" {
							if m.Type() == pmetric.MetricTypeSum {
								legacyFound = true
							}
							if m.Type() == pmetric.MetricTypeGauge {
								newFound = true
								if tt.expectLegacyAttrs {
									dp := m.Gauge().DataPoints().At(0)
									_, hasCPU := dp.Attributes().Get("cpu")
									assert.True(t, hasCPU, "expected legacy attr cpu")
									_, hasState := dp.Attributes().Get("state")
									assert.True(t, hasState, "expected legacy attr state")
								}
							}
						}
					}
				}
				assert.Equal(t, tt.expectLegacyMetric, legacyFound)
				assert.Equal(t, tt.expectNewMetric, newFound)
			})
		}
	})
}
