// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
)

// SystemCPUFrequencyMetricAttributeKey specifies the key of an attribute for the system.cpu.frequency metric.
type SystemCPUFrequencyMetricAttributeKey string

const (
	SystemCPUFrequencyMetricAttributeKeyCPU SystemCPUFrequencyMetricAttributeKey = "cpu"
)

// SystemCPUFrequencyMetricConfig provides config for the system.cpu.frequency metric.
type SystemCPUFrequencyMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUFrequencyMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUFrequencyMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUFrequencyMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUFrequencyMetricAttributeKeyCPU:
		default:
			return fmt.Errorf("metric system.cpu.frequency doesn't have an attribute %v, valid attributes: [cpu]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemCPUFrequencyV1MetricAttributeKey specifies the key of an attribute for the system.cpu.frequency@v1 metric.
type SystemCPUFrequencyV1MetricAttributeKey string

const (
	SystemCPUFrequencyV1MetricAttributeKeyCPULogicalNumber SystemCPUFrequencyV1MetricAttributeKey = "cpu.logical_number"
)

// SystemCPUFrequencyV1MetricConfig provides config for the system.cpu.frequency@v1 metric.
type SystemCPUFrequencyV1MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUFrequencyV1MetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUFrequencyV1MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUFrequencyV1MetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUFrequencyV1MetricAttributeKeyCPULogicalNumber:
		default:
			return fmt.Errorf("metric system.cpu.frequency@v1 doesn't have an attribute %v, valid attributes: [cpu.logical_number]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemCPULogicalCountMetricConfig provides config for the system.cpu.logical.count metric.
type SystemCPULogicalCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemCPULogicalCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SystemCPUPhysicalCountMetricConfig provides config for the system.cpu.physical.count metric.
type SystemCPUPhysicalCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemCPUPhysicalCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SystemCPUTimeMetricAttributeKey specifies the key of an attribute for the system.cpu.time metric.
type SystemCPUTimeMetricAttributeKey string

const (
	SystemCPUTimeMetricAttributeKeyCPU   SystemCPUTimeMetricAttributeKey = "cpu"
	SystemCPUTimeMetricAttributeKeyState SystemCPUTimeMetricAttributeKey = "state"
)

// SystemCPUTimeMetricConfig provides config for the system.cpu.time metric.
type SystemCPUTimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUTimeMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUTimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUTimeMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUTimeMetricAttributeKeyCPU, SystemCPUTimeMetricAttributeKeyState:
		default:
			return fmt.Errorf("metric system.cpu.time doesn't have an attribute %v, valid attributes: [cpu, state]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemCPUTimeV1MetricAttributeKey specifies the key of an attribute for the system.cpu.time@v1 metric.
type SystemCPUTimeV1MetricAttributeKey string

const (
	SystemCPUTimeV1MetricAttributeKeyCPULogicalNumber SystemCPUTimeV1MetricAttributeKey = "cpu.logical_number"
	SystemCPUTimeV1MetricAttributeKeyState            SystemCPUTimeV1MetricAttributeKey = "state"
)

// SystemCPUTimeV1MetricConfig provides config for the system.cpu.time@v1 metric.
type SystemCPUTimeV1MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                              `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUTimeV1MetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUTimeV1MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUTimeV1MetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUTimeV1MetricAttributeKeyCPULogicalNumber, SystemCPUTimeV1MetricAttributeKeyState:
		default:
			return fmt.Errorf("metric system.cpu.time@v1 doesn't have an attribute %v, valid attributes: [cpu.logical_number, state]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemCPUUtilizationMetricAttributeKey specifies the key of an attribute for the system.cpu.utilization metric.
type SystemCPUUtilizationMetricAttributeKey string

const (
	SystemCPUUtilizationMetricAttributeKeyCPU   SystemCPUUtilizationMetricAttributeKey = "cpu"
	SystemCPUUtilizationMetricAttributeKeyState SystemCPUUtilizationMetricAttributeKey = "state"
)

// SystemCPUUtilizationMetricConfig provides config for the system.cpu.utilization metric.
type SystemCPUUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUUtilizationMetricAttributeKeyCPU, SystemCPUUtilizationMetricAttributeKeyState:
		default:
			return fmt.Errorf("metric system.cpu.utilization doesn't have an attribute %v, valid attributes: [cpu, state]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for cpu metrics.
type MetricsConfig struct {
	SystemCPUFrequency     SystemCPUFrequencyMetricConfig     `mapstructure:"system.cpu.frequency"`
	SystemCPUFrequencyV1   SystemCPUFrequencyV1MetricConfig   `mapstructure:"system.cpu.frequency@v1"`
	SystemCPULogicalCount  SystemCPULogicalCountMetricConfig  `mapstructure:"system.cpu.logical.count"`
	SystemCPUPhysicalCount SystemCPUPhysicalCountMetricConfig `mapstructure:"system.cpu.physical.count"`
	SystemCPUTime          SystemCPUTimeMetricConfig          `mapstructure:"system.cpu.time"`
	SystemCPUTimeV1        SystemCPUTimeV1MetricConfig        `mapstructure:"system.cpu.time@v1"`
	SystemCPUUtilization   SystemCPUUtilizationMetricConfig   `mapstructure:"system.cpu.utilization"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SystemCPUFrequency: SystemCPUFrequencyMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemCPUFrequencyMetricAttributeKey{SystemCPUFrequencyMetricAttributeKeyCPU},
		},
		SystemCPUFrequencyV1: SystemCPUFrequencyV1MetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemCPUFrequencyV1MetricAttributeKey{SystemCPUFrequencyV1MetricAttributeKeyCPULogicalNumber},
		},
		SystemCPULogicalCount: SystemCPULogicalCountMetricConfig{
			Enabled: false,
		},
		SystemCPUPhysicalCount: SystemCPUPhysicalCountMetricConfig{
			Enabled: false,
		},
		SystemCPUTime: SystemCPUTimeMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SystemCPUTimeMetricAttributeKey{SystemCPUTimeMetricAttributeKeyCPU, SystemCPUTimeMetricAttributeKeyState},
		},
		SystemCPUTimeV1: SystemCPUTimeV1MetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemCPUTimeV1MetricAttributeKey{SystemCPUTimeV1MetricAttributeKeyCPULogicalNumber, SystemCPUTimeV1MetricAttributeKeyState},
		},
		SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemCPUUtilizationMetricAttributeKey{SystemCPUUtilizationMetricAttributeKeyCPU, SystemCPUUtilizationMetricAttributeKeyState},
		},
	}
}

// MetricsBuilderConfig is a configuration for cpu metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
