// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverHostmetricsEmitV1SemanticConventionsstageFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.hostmetrics.EmitV1SemanticConventionsstage",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, V1 Semantic Conventions are emmitted"),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45592"),
	featuregate.WithRegisterFromVersion("v0.145.0"),
)
